In [1]:
pip install sodapy

Requirement already satisfied: sodapy in c:\users\amd\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: requests>=2.20.0 in c:\users\amd\anaconda3\lib\site-packages (from sodapy) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\amd\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\amd\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\amd\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\amd\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2020.6.20)
Note: you may need to restart the kernel to use updated packages.

In [7]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us","V1l1F58oEE8H1XfoqElKC4EWG")

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofnewyork.us,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("qgc5-ecnb", limit=65219)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [14]:
results_df

,index,menu_item_id,year,restaurant_item_name,restaurant,restaurant_id,item_name,item_description,food_category,kids_meal,...,protein_text,potassium,potassium_100g,serving_size_text,calories_text,total_fat_text,saturated_fat_text,sodium_text,trans_fat_text,potassium_text
0,0,170040,2018,7 Eleven 100% Colombian Coffee,7 Eleven,1,100% Colombian Coffee,"100% Colombian Coffee, Coffee, Start My Day, T...",Beverages,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,170093,2018,7 Eleven 10 For $2 Mini Tacos,7 Eleven,1,10 For $2 Mini Tacos,"10 For $2 Mini Tacos, Late Night, Deals, Hot S...",Sandwiches,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,150023,2018,7 Eleven 2 for $1.69 Any Ring Donut,7 Eleven,1,2 for $1.69 Any Ring Donut,"2 for $1.69 Any Ring Donut, Bakery, Start My D...",Baked Goods,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,170067,2018,7 Eleven 5 For $4 Grill Mix N Match,7 Eleven,1,5 For $4 Grill Mix N Match,"5 For $4 Grill Mix N Match, Snacks, Hot Snacks...",Entrees,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,170112,2018,7 Eleven 6 Mini Breakfast Sausage Empanadas,7 Eleven,1,6 Mini Breakfast Sausage Empanadas,"6 Mini Breakfast Sausage Empanadas w/ Sausage,...",Sandwiches,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65214,65214,25779,2017,"Zaxby's Zax Sauce, 2 Portion Cups",Zaxby's,93,"Zax Sauce, 2 Portion Cups","Zax Sauce, for Chicken Finger Plate, Large & 1...",Toppings & Ingredients,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65215,65215,25780,2017,"Zaxby's Zax Sauce, 4 Portion Cups",Zaxby's,93,"Zax Sauce, 4 Portion Cups","Zax Sauce, for 20 Chicken Fingerz, Wings & Fin...",Toppings & Ingredients,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65216,65216,64609,2017,"Zaxby's Zax Sauce, Kidz",Zaxby's,93,"Zax Sauce, Kidz","Zax Sauce, for Kiddie Nibbler & Chicken Finger...",Toppings & Ingredients,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65217,65217,161751,2017,Zaxby's Zax Snak,Zaxby's,93,Zax Snak,"Zax Snak w/ Chicken Fingers, Texas Toast & Zax...",Appetizers & Sides,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65218,65218,25781,2017,"Zaxby's Zestable Sauce, 1 Portion Cup",Zaxby's,93,"Zestable Sauce, 1 Portion Cup","Zestable Sauce, 1 Portion Cup, for Onion Rings...",Toppings & Ingredients,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Imports
from pymongo import MongoClient
import pymongo

# Load csv dataset
data = results_df

# Connect to MongoDB
client =  MongoClient("mongodb+srv://dabteam:dab@cluster0.tqgtu.mongodb.net/test")
db = client['DAB_DATABASES']
collection = db['menu_information']
data.reset_index(inplace=True)
data_dict = data.to_dict("records")

# Insert collection
collection.insert_many(data_dict)

In [11]:
#sr_f.zipcode.unique()
m = len(pd.unique(results_df['restaurant']))
m

96